# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "email-marketing"
client_id = "9baf435d93b9286328d99abd1731c888"
application_url = "https://sperm-engineers-agreement-bolivia.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sperm-engineers-agreement-bolivia.trycloudflare.com/auth/callback",
  "https://sperm-engineers-agreement-bolivia.trycloudflare.com/auth/shopify/callback",
  "https://sperm-engineers-agreement-bolivia.trycloudflare.com/api/auth/callback",
  "https://sperm-engineers-agreement-bolivia.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-aee9ec3a.myshopify.com"
