# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "email-marketing"
client_id = "71c4db3ca1b754d2077031b2710818db"
application_url = "https://eye-workplace-exec-pop.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://eye-workplace-exec-pop.trycloudflare.com/auth/callback",
  "https://eye-workplace-exec-pop.trycloudflare.com/auth/shopify/callback",
  "https://eye-workplace-exec-pop.trycloudflare.com/api/auth/callback",
  "https://eye-workplace-exec-pop.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hongsonstore.myshopify.com"
